name: in4_solution
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1+3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  http_interceptor: ^2.0.0-beta.7
  in_app_update: ^4.2.2
  google_fonts: ^6.1.0
  overlay_support: ^2.0.1
  logger: ^2.0.1
  google_nav_bar: ^5.0.6
  local_auth: ^2.1.0
  geolocator: ^10.1.0
  image_picker: ^1.0.1
  shimmer: ^3.0.0
  intl: ^0.18.0
  font_awesome_flutter: ^10.1.0
  dropdown_button2: ^2.0.0
  calendar_date_picker2: ^0.5.2
  datepicker_dropdown: ^0.0.7
  flutter_image_compress: ^2.0.1
  connectivity_plus: ^5.0.0
  path_provider: ^2.0.13
  fluttertoast: ^8.2.1
  permission_handler: ^11.0.1
  connectivity_plus_web: ^1.2.5
  encrypted_shared_preferences: ^3.0.1
  duration_picker: ^1.1.1
  day_night_time_picker: ^1.2.0+2
  get: ^4.6.5
  top_snackbar_flutter: ^3.0.0+1
  animate_do: ^3.1.2
  location: ^5.0.3
  secure_shared_preferences: ^0.0.4
  file_picker: ^6.1.1

  nested: any
  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
