name: in4_solution
description: "HRM project."
publish_to: "none"

version: 1.1.0+3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  http_interceptor: ^2.0.0-beta.7
  in_app_update: ^4.2.2
  google_fonts: ^6.1.0
  overlay_support: ^2.0.1
  logger: ^2.0.1
  google_nav_bar: ^5.0.6
  local_auth: ^2.1.0
  geolocator: ^12.0.0
  image_picker: ^1.0.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  font_awesome_flutter: ^10.1.0
  dropdown_button2: ^2.0.0
  calendar_date_picker2: ^1.1.6
  datepicker_dropdown: ^0.1.4
  flutter_image_compress: ^2.3.0
  connectivity_plus: ^2.3.0
  path_provider: ^2.0.13
  fluttertoast: ^8.2.8
  permission_handler: ^11.0.1
  encrypted_shared_preferences: ^3.0.1
  duration_picker: ^1.1.1
  day_night_time_picker: ^1.2.0+2
  get: ^4.6.5
  top_snackbar_flutter: ^3.0.0+1
  animate_do: ^3.1.2
  location: ^7.0.0
  shared_preferences: ^2.3.2
  file_picker: ^8.0.7

  nested: any
  http: any
  flutter_secure_storage: ^9.2.2
  dev: ^1.0.0
  geolocator_web: ^4.0.0
  google_maps_flutter: ^2.10.0
  ntp: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/